# Generated by Django 4.2.6 on 2023-11-06 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('coach_id', models.AutoField(primary_key=True, serialize=False)),
                ('bio', models.TextField(blank=True, null=True)),
                ('last_update', models.DateTimeField()),
            ],
            options={
                'db_table': 'coach',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CoachCategory',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_update', models.DateTimeField()),
            ],
            options={
                'db_table': 'coach_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CoachReview',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.PositiveIntegerField()),
                ('review_text', models.TextField()),
                ('review_date', models.DateField()),
            ],
            options={
                'db_table': 'coach_review',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EquipmentForExercise',
            fields=[
                ('exercise_equipment_id', models.AutoField(primary_key=True, serialize=False)),
                ('last_update', models.DateTimeField()),
            ],
            options={
                'db_table': 'equipment_for_exercise',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('exercise_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('muscle_group_id', models.PositiveIntegerField(blank=True, null=True)),
                ('last_update', models.DateTimeField()),
            ],
            options={
                'db_table': 'exercise',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExerciseCategory',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('last_update', models.DateTimeField()),
            ],
            options={
                'db_table': 'exercise_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExerciseEquipment',
            fields=[
                ('equipment_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('last_update', models.DateTimeField()),
            ],
            options={
                'db_table': 'exercise_equipment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExerciseInWorkoutPlan',
            fields=[
                ('exercise_in_plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('sets', models.IntegerField(blank=True, null=True)),
                ('reps', models.IntegerField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('calories', models.IntegerField(blank=True, null=True)),
                ('complete_by_date', models.DateField()),
                ('last_update', models.DateTimeField()),
            ],
            options={
                'db_table': 'exercise_in_workout_plan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExerciseMedia',
            fields=[
                ('media_id', models.AutoField(primary_key=True, serialize=False)),
                ('media_type', models.CharField(max_length=5)),
                ('media_url', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('upload_date', models.DateField()),
                ('last_update', models.DateTimeField()),
            ],
            options={
                'db_table': 'exercise_media',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExerciseMuscleCategory',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('last_update', models.DateTimeField()),
            ],
            options={
                'db_table': 'exercise_muscle_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FitnessGoal',
            fields=[
                ('goal_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('creation_date', models.DateField()),
                ('date_to_complete', models.DateField()),
                ('achieved', models.IntegerField(blank=True, null=True)),
                ('last_update', models.DateTimeField()),
            ],
            options={
                'db_table': 'fitness_goal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IntakeLog',
            fields=[
                ('intake_id', models.AutoField(primary_key=True, serialize=False)),
                ('intake_type', models.CharField(max_length=7)),
                ('amount', models.PositiveIntegerField()),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'intake_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MentalHealthLog',
            fields=[
                ('health_id', models.AutoField(primary_key=True, serialize=False)),
                ('stress_level', models.CharField(max_length=6)),
                ('sleep_quality', models.CharField(max_length=9)),
                ('mood', models.CharField(max_length=7)),
                ('recorded_date', models.DateField()),
            ],
            options={
                'db_table': 'mental_health_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('message_text', models.TextField()),
                ('sent_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'message',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_date', models.DateField()),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=255, null=True)),
                ('last_update', models.DateTimeField()),
            ],
            options={
                'db_table': 'payment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhysicalHealthLog',
            fields=[
                ('health_id', models.AutoField(primary_key=True, serialize=False)),
                ('measure_type', models.CharField(max_length=6)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'physical_health_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProgressPhoto',
            fields=[
                ('photo_id', models.AutoField(primary_key=True, serialize=False)),
                ('photo_path', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'progress_photo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=255)),
                ('last_update', models.DateTimeField()),
            ],
            options={
                'db_table': 'state',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('subscription_id', models.AutoField(primary_key=True, serialize=False)),
                ('subscription_start_date', models.DateField(blank=True, null=True)),
                ('subscription_end_date', models.DateField(blank=True, null=True)),
                ('isActive', models.IntegerField(blank=True, db_column='isActive', null=True)),
                ('last_update', models.DateTimeField()),
            ],
            options={
                'db_table': 'subscription',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, max_length=6, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(blank=True, null=True)),
                ('last_update', models.DateTimeField()),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WeightGoal',
            fields=[
                ('goal_id', models.AutoField(primary_key=True, serialize=False)),
                ('target_weight', models.PositiveIntegerField()),
                ('creation_date', models.DateField()),
                ('date_to_complete', models.DateField()),
                ('achieved', models.IntegerField(blank=True, null=True)),
                ('last_update', models.DateTimeField()),
            ],
            options={
                'db_table': 'weight_goal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WorkoutLog',
            fields=[
                ('workout_id', models.AutoField(primary_key=True, serialize=False)),
                ('coach_id', models.PositiveIntegerField(blank=True, null=True)),
                ('workout_date', models.DateField()),
                ('sets', models.PositiveIntegerField(blank=True, null=True)),
                ('reps', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'workout_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('plan_name', models.CharField(max_length=255)),
                ('creation_date', models.DateField()),
                ('last_update', models.DateTimeField()),
            ],
            options={
                'db_table': 'workout_plan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserCredentials',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='FitConnect.user')),
                ('salt', models.CharField(max_length=64)),
                ('hashed_password', models.CharField(max_length=64)),
                ('last_update', models.DateTimeField()),
            ],
            options={
                'db_table': 'user_credentials',
                'managed': False,
            },
        ),
    ]
