# Generated by Django 4.2.6 on 2023-11-08 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FitConnect', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coach',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='coachcategory',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='coachreview',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='equipmentforexercise',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='exercise',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='exercisecategory',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='exerciseequipment',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='exerciseinworkoutplan',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='exercisemedia',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='exercisemusclecategory',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='fitnessgoal',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='intakelog',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='mentalhealthlog',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='physicalhealthlog',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='progressphoto',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='usercredentials',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='weightgoal',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='workoutlog',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='workoutplan',
            options={'managed': True},
        ),
    ]
