# Generated by Django 4.2.6 on 2023-11-08 20:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FitConnect', '0002_alter_coach_options_alter_coachcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coach',
            options={},
        ),
        migrations.AlterModelOptions(
            name='coachcategory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='coachreview',
            options={},
        ),
        migrations.AlterModelOptions(
            name='equipmentforexercise',
            options={},
        ),
        migrations.AlterModelOptions(
            name='exercise',
            options={},
        ),
        migrations.AlterModelOptions(
            name='exercisecategory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='exerciseequipment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='exerciseinworkoutplan',
            options={},
        ),
        migrations.AlterModelOptions(
            name='exercisemedia',
            options={},
        ),
        migrations.AlterModelOptions(
            name='exercisemusclecategory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='fitnessgoal',
            options={},
        ),
        migrations.AlterModelOptions(
            name='intakelog',
            options={},
        ),
        migrations.AlterModelOptions(
            name='mentalhealthlog',
            options={},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='physicalhealthlog',
            options={},
        ),
        migrations.AlterModelOptions(
            name='progressphoto',
            options={},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelOptions(
            name='usercredentials',
            options={},
        ),
        migrations.AlterModelOptions(
            name='weightgoal',
            options={},
        ),
        migrations.AlterModelOptions(
            name='workoutlog',
            options={},
        ),
        migrations.AlterModelOptions(
            name='workoutplan',
            options={},
        ),
        migrations.AddField(
            model_name='coach',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='FitConnect.coachcategory'),
        ),
        migrations.AddField(
            model_name='coach',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='FitConnect.state'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coach',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='FitConnect.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coachreview',
            name='coach',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='FitConnect.coach'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coachreview',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='FitConnect.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipmentforexercise',
            name='equipment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='FitConnect.exerciseequipment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipmentforexercise',
            name='exercise',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='FitConnect.exercise'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercise',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='FitConnect.exercisecategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exerciseinworkoutplan',
            name='exercise',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='FitConnect.exercise'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exerciseinworkoutplan',
            name='plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='FitConnect.workoutplan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercisemedia',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='FitConnect.coach'),
        ),
        migrations.AddField(
            model_name='exercisemedia',
            name='exercise',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='FitConnect.exercise'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercisemedia',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='FitConnect.user'),
        ),
        migrations.AddField(
            model_name='fitnessgoal',
            name='exercise',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='FitConnect.exercise'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fitnessgoal',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='FitConnect.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intakelog',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='FitConnect.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentalhealthlog',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='FitConnect.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='recipient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='message_recipient_set', to='FitConnect.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='FitConnect.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='subscription',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='FitConnect.subscription'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='FitConnect.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='physicalhealthlog',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='FitConnect.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='progressphoto',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='FitConnect.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='coach',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='FitConnect.coach'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='subscriber',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='FitConnect.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weightgoal',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='FitConnect.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workoutlog',
            name='exercise_in_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='FitConnect.exerciseinworkoutplan'),
        ),
        migrations.AddField(
            model_name='workoutlog',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='FitConnect.workoutplan'),
        ),
        migrations.AddField(
            model_name='workoutlog',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='FitConnect.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='FitConnect.coach'),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='FitConnect.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coach',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='coachcategory',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='equipmentforexercise',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='exercisecategory',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='exerciseequipment',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='exerciseinworkoutplan',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='exercisemedia',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='exercisemusclecategory',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='fitnessgoal',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='payment',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='state',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='usercredentials',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='weightgoal',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
